package by.yurovski.enums;

public enum CommandEnum {
    EMPTY,
    ERROR,
    REGISTRATION_PAGE_REDIRECT,
    IMG_PAGE_REDIRECT,
    USER_ACCOUNT_REDIRECT,
    FOLLOWERS_REDIRECT,
    FOLLOWINGS_REDIRECT,
    LOGIN_PAGE_REDIRECT,
    USERLIST_PAGE_REDIRECT,
    FOTO_PAGE_REDIRECT,
    REGISTRATION,
    LOG_IN,
    LOG_OUT,
    DELETE_ACCOUNT,
    ADD_NEW_IMG,
    ADD_NEW_COMMENT,
    DELETE_COMMENT,
    DELETE_IMG,
    LIKE_IMG,
    LIKE_COMMENT,
    FOLLOW_UNFOLLOW,
    FOTO_SORT,
    USER_SORT,
    COMMENT_SORT,
    CHANGE_LOCALE,
    FORGOT_PASSWORD,
    EDIT_FOTO,
    EDIT_USER;

}
